package com.ninyjun.tinyerp.account.acctsvc.repository;

import com.ninyjun.tinyerp.account.acctsdk.model.Account;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Delete({
        "delete from ACCOUNT",
        "where ACCT_ID = #{acctId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long acctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Insert({
        "insert into ACCOUNT (ACCT_ID, ACCT_NAME, ",
        "ACCT_DESCRIBE, CREATE_TIME, ",
        "CREATE_EMP_ID, CREATE_DEPART_ID)",
        "values (#{acctId,jdbcType=BIGINT}, #{acctName,jdbcType=VARCHAR}, ",
        "#{acctDescribe,jdbcType=VARCHAR}, sysdate(), ",
        "#{createEmpId,jdbcType=VARCHAR}, #{createDepartId,jdbcType=VARCHAR})"
    })
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Select({
        "select",
        "ACCT_ID, ACCT_NAME, ACCT_DESCRIBE, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from ACCOUNT",
        "where ACCT_ID = #{acctId,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="ACCT_NAME", property="acctName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCT_DESCRIBE", property="acctDescribe", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    Account selectByPrimaryKey(Long acctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Select({
        "select",
        "ACCT_ID, ACCT_NAME, ACCT_DESCRIBE, CREATE_TIME, CREATE_EMP_ID, CREATE_DEPART_ID",
        "from ACCOUNT"
    })
    @Results({
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="ACCT_NAME", property="acctName", jdbcType=JdbcType.VARCHAR),
        @Result(column="ACCT_DESCRIBE", property="acctDescribe", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_EMP_ID", property="createEmpId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_DEPART_ID", property="createDepartId", jdbcType=JdbcType.VARCHAR)
    })
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Update({
        "update ACCOUNT",
        "set ACCT_NAME = #{acctName,jdbcType=VARCHAR},",
          "ACCT_DESCRIBE = #{acctDescribe,jdbcType=VARCHAR},",
          "CREATE_TIME = sysdate(),",
          "CREATE_EMP_ID = #{createEmpId,jdbcType=VARCHAR},",
          "CREATE_DEPART_ID = #{createDepartId,jdbcType=VARCHAR}",
        "where ACCT_ID = #{acctId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Account record);
}