package com.ninyjun.tinyerp.account.acctsvc.repository;

import com.ninyjun.tinyerp.account.acctsdk.model.AccountExtra;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AccountExtraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Delete({
        "delete from ACCOUNT_EXTRA",
        "where ACCT_ID = #{acctId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("acctId") Long acctId, @Param("propertyCode") String propertyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Insert({
        "insert into ACCOUNT_EXTRA (ACCT_ID, PROPERTY_CODE, ",
        "PROPERTY_VALUE)",
        "values (#{acctId,jdbcType=BIGINT}, #{propertyCode,jdbcType=VARCHAR}, ",
        "#{propertyValue,jdbcType=VARCHAR})"
    })
    int insert(AccountExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Select({
        "select",
        "ACCT_ID, PROPERTY_CODE, PROPERTY_VALUE",
        "from ACCOUNT_EXTRA",
        "where ACCT_ID = #{acctId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    AccountExtra selectByPrimaryKey(@Param("acctId") Long acctId, @Param("propertyCode") String propertyCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Select({
        "select",
        "ACCT_ID, PROPERTY_CODE, PROPERTY_VALUE",
        "from ACCOUNT_EXTRA"
    })
    @Results({
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    List<AccountExtra> selectAll();


    @Select({
            "select",
            "ACCT_ID, PROPERTY_CODE, PROPERTY_VALUE",
            "from ACCOUNT_EXTRA",
            " where ACCT_ID = #{acctId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="PROPERTY_CODE", property="propertyCode", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="PROPERTY_VALUE", property="propertyValue", jdbcType=JdbcType.VARCHAR)
    })
    List<AccountExtra> selectByAcctId(Long acctId);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_EXTRA
     *
     * @mbg.generated Fri Nov 29 17:36:34 CST 2019
     */
    @Update({
        "update ACCOUNT_EXTRA",
        "set PROPERTY_VALUE = #{propertyValue,jdbcType=VARCHAR}",
        "where ACCT_ID = #{acctId,jdbcType=BIGINT}",
          "and PROPERTY_CODE = #{propertyCode,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(AccountExtra record);
}