package com.ninyjun.tinyerp.account.acctsvc.repository;

import com.ninyjun.tinyerp.account.acctsdk.model.AccountBankAcctno;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface AccountBankAcctnoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BANK_ACCTNO
     *
     * @mbg.generated Sat Nov 30 16:58:15 CST 2019
     */
    @Delete({
        "delete from ACCOUNT_BANK_ACCTNO",
        "where ACCT_ID = #{acctId,jdbcType=BIGINT}",
          "and BANK_ACCTNO = #{bankAcctno,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(@Param("acctId") Long acctId, @Param("bankAcctno") String bankAcctno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BANK_ACCTNO
     *
     * @mbg.generated Sat Nov 30 16:58:15 CST 2019
     */
    @Insert({
        "insert into ACCOUNT_BANK_ACCTNO (ACCT_ID, BANK_ACCTNO, ",
        "BANK_CODE, BANK_ACCTNO_NAME)",
        "values (#{acctId,jdbcType=BIGINT}, #{bankAcctno,jdbcType=VARCHAR}, ",
        "#{bankCode,jdbcType=INTEGER}, #{bankAcctnoName,jdbcType=VARCHAR})"
    })
    int insert(AccountBankAcctno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BANK_ACCTNO
     *
     * @mbg.generated Sat Nov 30 16:58:15 CST 2019
     */
    @Select({
        "select",
        "ACCT_ID, BANK_ACCTNO, BANK_CODE, BANK_ACCTNO_NAME",
        "from ACCOUNT_BANK_ACCTNO",
        "where ACCT_ID = #{acctId,jdbcType=BIGINT}",
          "and BANK_ACCTNO = #{bankAcctno,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="BANK_ACCTNO", property="bankAcctno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BANK_CODE", property="bankCode", jdbcType=JdbcType.INTEGER),
        @Result(column="BANK_ACCTNO_NAME", property="bankAcctnoName", jdbcType=JdbcType.VARCHAR)
    })
    AccountBankAcctno selectByPrimaryKey(@Param("acctId") Long acctId, @Param("bankAcctno") String bankAcctno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BANK_ACCTNO
     *
     * @mbg.generated Sat Nov 30 16:58:15 CST 2019
     */
    @Select({
        "select",
        "ACCT_ID, BANK_ACCTNO, BANK_CODE, BANK_ACCTNO_NAME",
        "from ACCOUNT_BANK_ACCTNO"
    })
    @Results({
        @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="BANK_ACCTNO", property="bankAcctno", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="BANK_CODE", property="bankCode", jdbcType=JdbcType.INTEGER),
        @Result(column="BANK_ACCTNO_NAME", property="bankAcctnoName", jdbcType=JdbcType.VARCHAR)
    })
    List<AccountBankAcctno> selectAll();



    @Select({
            "select",
            "ACCT_ID, BANK_ACCTNO, BANK_CODE, BANK_ACCTNO_NAME",
            "from ACCOUNT_BANK_ACCTNO",
            " where ACCT_ID = #{acctId,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column="ACCT_ID", property="acctId", jdbcType=JdbcType.BIGINT, id=true),
            @Result(column="BANK_ACCTNO", property="bankAcctno", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="BANK_CODE", property="bankCode", jdbcType=JdbcType.INTEGER),
            @Result(column="BANK_ACCTNO_NAME", property="bankAcctnoName", jdbcType=JdbcType.VARCHAR)
    })
    List<AccountBankAcctno> selectByAcctId(Long acctId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACCOUNT_BANK_ACCTNO
     *
     * @mbg.generated Sat Nov 30 16:58:15 CST 2019
     */
    @Update({
        "update ACCOUNT_BANK_ACCTNO",
        "set BANK_CODE = #{bankCode,jdbcType=INTEGER},",
          "BANK_ACCTNO_NAME = #{bankAcctnoName,jdbcType=VARCHAR}",
        "where ACCT_ID = #{acctId,jdbcType=BIGINT}",
          "and BANK_ACCTNO = #{bankAcctno,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(AccountBankAcctno record);
}