package com.ninyjun.tinyerp.account.acctsdk.model;

public class AccountExtra {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT_EXTRA.ACCT_ID
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    private Long acctId;

    @Override
    public String toString() {
        return "AccountExtra{" +
                "acctId=" + acctId +
                ", propertyCode='" + propertyCode + '\'' +
                ", propertyValue='" + propertyValue + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    private String propertyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    private String propertyValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT_EXTRA.ACCT_ID
     *
     * @return the value of ACCOUNT_EXTRA.ACCT_ID
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public Long getAcctId() {
        return acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT_EXTRA.ACCT_ID
     *
     * @param acctId the value for ACCOUNT_EXTRA.ACCT_ID
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public void setAcctId(Long acctId) {
        this.acctId = acctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT_EXTRA.PROPERTY_CODE
     *
     * @return the value of ACCOUNT_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public String getPropertyCode() {
        return propertyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT_EXTRA.PROPERTY_CODE
     *
     * @param propertyCode the value for ACCOUNT_EXTRA.PROPERTY_CODE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public void setPropertyCode(String propertyCode) {
        this.propertyCode = propertyCode == null ? null : propertyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT_EXTRA.PROPERTY_VALUE
     *
     * @return the value of ACCOUNT_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT_EXTRA.PROPERTY_VALUE
     *
     * @param propertyValue the value for ACCOUNT_EXTRA.PROPERTY_VALUE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }
}