package com.ninyjun.tinyerp.account.acctsdk.model;

public class AccountBalanceType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_CODE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    private Integer acctBalanceTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_NAME
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    private String acctBalanceTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT_BALANCE_TYPE.TYPE_CATALOG
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    private Integer typeCatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACCOUNT_BALANCE_TYPE.TYPE_DESCRIBE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    private String typeDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_CODE
     *
     * @return the value of ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_CODE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public Integer getAcctBalanceTypeCode() {
        return acctBalanceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_CODE
     *
     * @param acctBalanceTypeCode the value for ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_CODE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public void setAcctBalanceTypeCode(Integer acctBalanceTypeCode) {
        this.acctBalanceTypeCode = acctBalanceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_NAME
     *
     * @return the value of ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_NAME
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public String getAcctBalanceTypeName() {
        return acctBalanceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_NAME
     *
     * @param acctBalanceTypeName the value for ACCOUNT_BALANCE_TYPE.ACCT_BALANCE_TYPE_NAME
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public void setAcctBalanceTypeName(String acctBalanceTypeName) {
        this.acctBalanceTypeName = acctBalanceTypeName == null ? null : acctBalanceTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT_BALANCE_TYPE.TYPE_CATALOG
     *
     * @return the value of ACCOUNT_BALANCE_TYPE.TYPE_CATALOG
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public Integer getTypeCatalog() {
        return typeCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT_BALANCE_TYPE.TYPE_CATALOG
     *
     * @param typeCatalog the value for ACCOUNT_BALANCE_TYPE.TYPE_CATALOG
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public void setTypeCatalog(Integer typeCatalog) {
        this.typeCatalog = typeCatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACCOUNT_BALANCE_TYPE.TYPE_DESCRIBE
     *
     * @return the value of ACCOUNT_BALANCE_TYPE.TYPE_DESCRIBE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public String getTypeDescribe() {
        return typeDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACCOUNT_BALANCE_TYPE.TYPE_DESCRIBE
     *
     * @param typeDescribe the value for ACCOUNT_BALANCE_TYPE.TYPE_DESCRIBE
     *
     * @mbg.generated Sat Nov 30 11:41:45 CST 2019
     */
    public void setTypeDescribe(String typeDescribe) {
        this.typeDescribe = typeDescribe == null ? null : typeDescribe.trim();
    }
}